# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CD .NET

on:
  pull_request:
    branches: [ "master", "feature/CICD" ]
    # On PR Merged on master
  # pull_request:
  #   types:
  #   - closed
  #   branches:
  #   - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Chackout Project
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build -c Release -verbosity:minimal

    - name: Create msi
      shell: pwsh
      run: |
        dotnet tool install --global wix
        wix build ./SpeechSynth.wxs

    - name: Upload MSI for Windows to release page
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "windows"
        prerelease: true
        title: "Windows Development Build"
        files: |
          SpeetchSynth.exe.msi
